export enum roles {
  ADMIN = "ADMIN",
  AGENT = "AGENT",
  COMPANY_ADMIN = "COMPANY_ADMIN",
  COMPANY_USER = "COMPANY_USER",
  DEVELOPER = "DEVELOPER",
  ADMINISTRATOR = "ADMINISTRATOR",
  MANAGER = "MANAGER",
  STAFF = "STAFF",
  CLIENT = "CLIENT",
}

export enum permissions {
  ALL = "ALL",
  DEFAULT = "DEFAULT",
  CREATE_USER = "CREATE_USER",
  DELETE_USER = "DELETE_USER",
  UPDATE_USER = "UPDATE_USER",
  VIEW_USER = "VIEW_USER",
  MANAGE_ROLES = "MANAGE_ROLES",
  MANAGE_PERMISSIONS = "MANAGE_PERMISSIONS",
}
